apiVersion: v1
kind: Service
metadata:
  labels:
    app: survey-server
  name: survey-server
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: survey-server
  type: LoadBalancer
